production:
  video_bucket: mandarinbanana-assets
  image_bucket: mandarinbanana-paintings
  fimage_bucket: mandarinbanana-featured-paintings
  region: eu-west-1

development:
  video_bucket: mandarinbanana-dev
  image_bucket: mandarinbanana-dev
  fimage_bucket: mandarinbanana-dev
  region: eu-west-1

test:
  video_bucket: mandarinbanana-test
  image_bucket: mandarinbanana-test
  fimage_bucket: mandarinbanana-test
  region: eu-west-1
